# Generated by Django 4.2 on 2024-06-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_checkboxnotetype_defaultnotetype_imagenotetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkboxnotetype',
            name='checkbox_list',
        ),
        migrations.RemoveField(
            model_name='checkboxnotetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='defaultnotetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='imagenotetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='imagenotetype',
            name='image',
        ),
        migrations.AlterField(
            model_name='checkboxnotetype',
            name='note_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkbox_notes', to='notes.notetype'),
        ),
        migrations.AlterField(
            model_name='defaultnotetype',
            name='note_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_notes', to='notes.notetype'),
        ),
        migrations.AlterField(
            model_name='imagenotetype',
            name='note_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_notes', to='notes.notetype'),
        ),
    ]
